<?php
namespace undertow\theme;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-25 at 14:57:05.
 */
class PageTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Page
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->DI = new \undertow\dependencyinjection\DependencyInjection( new \undertow\dependencyinjection\ContainerOfObjects() );
        $this->object = $this->DI->get('\\undertow\\theme\\Page', __DIR__.DIRECTORY_SEPARATOR.'PageTestTemplate.tpl');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers undertow\theme\Page::setData
     * @todo   Implement testSetData().
     */
    public function testSetData()
    {
        $this->object->setData(array('name'=>'Henrik'));
        $d = $this->object->render();
        $this->assertEquals($d, '<div id="testFile">Henrik</div>');
    }

    /**
     * @covers undertow\theme\Page::render
     * @todo   Implement testRender().
     */
    public function testRender()
    {
        $this->object->setData(array('name'=>'Henrik'));
        $d = $this->object->render();
        $this->assertEquals($d, '<div id="testFile">Henrik</div>');

    }

    /**
     * @covers undertow\theme\Page::checkEndTag
     * @todo   Implement testCheckEndTag().
     */
    public function testCheckEndTag()
    {
        $tag = 'doctype';
        $this->object->checkEndTag($tag);
        $this->assertNull($tag);
    }

    /**
     * @covers undertow\theme\Page::checkTag
     * @todo   Implement testCheckTag().
     */
    public function testCheckTag()
    {
        $tag = 'doctype';
        $attr = NULL;
        $cont = NULL;
        $this->object->checkTag($tag,$attr,$cont);
        $this->assertEquals($tag, '!DOCTYPE html');
    }
}
